COLUMNS:
  Lead_Origin: object 
  Lead_Source: object 
  Do_Not_Email: object 
  Do_Not_Call: object 
  Converted: int64  
  Total_Visits: float64
  Total_Time_Spent_on_Website: float64
  Page_Views_Per_Visit: float64
  Last_Activity: object 
  Country: object 
  Specialization: object 
  How_did_you_hear_about_X_Education: object 
  Current_Occupation: object 
  Reason_for_Choosing_Course: object 
  Search: object 
  Newspaper_Article: object 
  X_Education_Forums: object 
  Newspaper: object 
  Digital_Advertisement: object 
  Through_Recommendations: object 
  Tags: object 
  Lead_Quality: object 
  Lead_Profile: object 
  City: object 
  Asymmetric_Activity_Index: object 
  Asymmetric_Profile_Index: object 
  Asymmetric_Activity_Score: float64
  Asymmetric_Profile_Score: float64
  A_free_copy_of_Mastering_The_Interview: object 
  Last_Notable_Activity: object 

TARGET_COLUMN:
  name: Converted