artifacts_root: artifacts

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/lead.csv
  numerical_cols:
    - 'Total_Visits'
    - 'Total_Time_Spent_on_Website'
    - 'Page_Views_Per_Visit'
    - 'Asymmetric_Activity_Score'
    - 'Asymmetric_Profile_Score'
             
  categorical_cols: 
    - "Lead_Origin"
    - "Lead_Source" 
    - "Do_Not_Email" 
    - "Do_Not_Call" 
    - "Last_Activity"
    - "Country" 
    - "Specialization" 
    - "How_did_you_hear_about_X_Education"
    - "Current_Occupation"
    - "Reason_for_Choosing_Course" 
    - "Search" 
    - "Newspaper_Article" 
    - "X_Education_Forums" 
    - "Newspaper" 
    - "Digital_Advertisement" 
    - "Through_Recommendations" 
    - "Tags" 
    - "Lead_Quality" 
    - "Lead_Profile" 
    - "City" 
    - "Asymmetric_Activity_Index" 
    - "Asymmetric_Profile_Index" 
    - "A_free_copy_of_Mastering_The_Interview" 
    - "Last_Notable_Activity" 
 




