artifacts_root: artifacts

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/lead.csv
  STATUS_FILE: artifacts/data_validation/status.json 
  critical_columns:
    - "Lead_Origin"
    - "Lead_Source" 
    - "Do_Not_Email" 
    - "Do_Not_Call" 
    - "Converted"  
    - "Total_Visits"
    - "Total_Time_Spent_on_Website"
    - "Page_Views_Per_Visit"
    - "Last_Activity" 
    - "Country" 
    - "Specialization" 
    - "How_did_you_hear_about_X_Education" 
    - "Current_Occupation" 
    - "Reason_for_Choosing_Course" 
    - "Search" 
    - "Newspaper_Article" 
    - "X_Education_Forums" 
    - "Newspaper" 
    - "Digital_Advertisement" 
    - "Through_Recommendations" 
    - "Tags" 
    - "Lead_Quality" 
    - "Lead_Profile" 
    - "City" 
    - "Asymmetric_Activity_Index" 
    - "Asymmetric_Profile_Index" 
    - "Asymmetric_Activity_Score"
    - "Asymmetric_Profile_Score"
    - "A_free_copy_of_Mastering_The_Interview" 
    - "Last_Notable_Activity" 
  data_ranges:
    Converted:
      min: 0
      max: 1
    TotalVisits:
      min: 0
      max: 300
    Total Time Spent on Website:
      min: 0 
      max: 2500 
    Page Views Per Visit:
      min: 0
      max: 75
    Asymmetrique Activity Score:
      min: 0
      max: 100
    Asymmetrique Profile Score:
      min: 0
      max: 100
