artifacts_root: artifacts

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/lead.csv
  numerical_cols:
    - 'TotalVisits'
    - 'Total Time Spent on Website'
    - 'Page Views Per Visit'
    - 'Asymmetrique Activity Score'
    - 'Asymmetrique Profile Score'
             
  categorical_cols:
    - "Lead Origin" 
    - "Lead Source"
    - "Do Not Email"
    - "Do Not Call"
    - "Last Activity" 
    - "Country" 
    - "Specialization" 
    - "How did you hear about X Education" 
    - "What is your current occupation" 
    - "What matters most to you in choosing a course" 
    - "Search" 
    - "Newspaper Article" 
    - "X Education Forums" 
    - "Newspaper" 
    - "Digital Advertisement" 
    - "Through Recommendations" 
    - "Tags" 
    - "Lead Quality" 
    - "Lead Profile" 
    - "City" 
    - "Asymmetrique Activity Index" 
    - "Asymmetrique Profile Index" 
    - "A free copy of Mastering The Interview" 
    - "Last Notable Activity" 
    



